function FileData_Pairs(x)
{
x.t("insights","home");
x.t("home","back");
x.t("u.s","patents");
x.t("notices","section");
x.t("back","top");
x.t("top","2014");
x.t("installing","configuring");
x.t("complete","patent");
x.t("configuring","database");
x.t("vendors","installing");
x.t("performance","supported");
x.t("performance","database");
x.t("performance","module");
x.t("patent","notice");
x.t("legal","notices");
x.t("supported","database");
x.t("notice","legal");
x.t("2014","riverbed");
x.t("software","may");
x.t("may","covered");
x.t("section","riverbed");
x.t("database","insights");
x.t("database","vendors");
x.t("database","performance");
x.t("technology","software");
x.t("module","database");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("covered","u.s");
x.t("patents","complete");
}
