function FileData_Pairs(x)
{
x.t("appresponse","supported");
x.t("home","back");
x.t("u.s","patents");
x.t("video","codecs");
x.t("notices","section");
x.t("sections","list");
x.t("back","top");
x.t("top","2014");
x.t("list","codecs");
x.t("codecs","home");
x.t("codecs","voip");
x.t("codecs","supported");
x.t("codecs","following");
x.t("complete","patent");
x.t("voip","performance");
x.t("performance","supported");
x.t("patent","notice");
x.t("legal","notices");
x.t("supported","appresponse");
x.t("supported","video");
x.t("supported","codecs");
x.t("supported","voice");
x.t("supported","audio");
x.t("voice","codecs");
x.t("notice","legal");
x.t("2014","riverbed");
x.t("software","may");
x.t("may","covered");
x.t("section","riverbed");
x.t("technology","software");
x.t("audio","codecs");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("following","sections");
x.t("covered","u.s");
x.t("patents","complete");
}
