function FileData_Pairs(x)
{
x.t("right","corner");
x.t("home","back");
x.t("u.s","patents");
x.t("user","interface");
x.t("interface","help");
x.t("notices","section");
x.t("back","top");
x.t("top","2014");
x.t("clicking","bottom");
x.t("menu","insight");
x.t("menu","help");
x.t("menu","online");
x.t("corner","home");
x.t("complete","patent");
x.t("kit","user");
x.t("kit","(idk)");
x.t("accessed","clicking");
x.t("patent","notice");
x.t("legal","notices");
x.t("notice","legal");
x.t("2014","riverbed");
x.t("software","may");
x.t("may","covered");
x.t("section","riverbed");
x.t("insight","development");
x.t("technology","software");
x.t("help","menu");
x.t("help","accessed");
x.t("(idk)","insight");
x.t("online","help");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("bottom","right");
x.t("development","kit");
x.t("covered","u.s");
x.t("patents","complete");
}
