function FileData_Pairs(x)
{
x.t("appresponse","xpert");
x.t("home","back");
x.t("u.s","patents");
x.t("download","additional");
x.t("support","site");
x.t("notices","section");
x.t("product","home");
x.t("back","top");
x.t("top","2014");
x.t("complete","patent");
x.t("navigate","software");
x.t("https://support.riverbed.com","navigate");
x.t("patent","notice");
x.t("legal","notices");
x.t("notice","legal");
x.t("software","may");
x.t("software","documentation");
x.t("2014","riverbed");
x.t("may","covered");
x.t("section","riverbed");
x.t("documentation","download");
x.t("documentation","additional");
x.t("documentation","page");
x.t("documentation","resources");
x.t("technology","software");
x.t("additional","documentation");
x.t("site","https://support.riverbed.com");
x.t("page","appresponse");
x.t("xpert","product");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("covered","u.s");
x.t("resources","riverbed");
x.t("patents","complete");
}
