function FileData_Pairs(x)
{
x.t("home","back");
x.t("u.s","patents");
x.t("user","guide");
x.t("predicting","application");
x.t("notices","section");
x.t("support","center");
x.t("back","top");
x.t("top","2013");
x.t("complete","patent");
x.t("guide","predicting");
x.t("performance","user");
x.t("performance","predicting");
x.t("performance","quickpredict");
x.t("quickrecode","home");
x.t("patent","notice");
x.t("legal","notices");
x.t("notice","legal");
x.t("2013","riverbed");
x.t("software","may");
x.t("may","covered");
x.t("section","riverbed");
x.t("technology","software");
x.t("quickpredict","quickrecode");
x.t("application","performance");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("covered","u.s");
x.t("patents","complete");
}
