function FileData_Pairs(x)
{
x.t("protocols","home");
x.t("protocols","user");
x.t("protocols","supported");
x.t("protocols","following");
x.t("home","back");
x.t("u.s","patents");
x.t("user","guide");
x.t("notices","section");
x.t("support","center");
x.t("trace","sources");
x.t("back","top");
x.t("top","2013");
x.t("complete","patent");
x.t("guide","appendices");
x.t("appendices","supported");
x.t("patent","notice");
x.t("legal","notices");
x.t("supported","protocols");
x.t("supported","packet");
x.t("notice","legal");
x.t("2013","riverbed");
x.t("software","may");
x.t("may","covered");
x.t("section","riverbed");
x.t("sources","protocols");
x.t("sources","supported");
x.t("technology","software");
x.t("topics","supported");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("packet","trace");
x.t("following","topics");
x.t("covered","u.s");
x.t("patents","complete");
}
