function FileData_Pairs(x)
{
x.t("home","back");
x.t("u.s","patents");
x.t("user","guide");
x.t("notices","section");
x.t("support","center");
x.t("back","top");
x.t("top","2013");
x.t("complete","patent");
x.t("guide","analyzing");
x.t("network","tier");
x.t("appdoctor","troubleshooting");
x.t("patent","notice");
x.t("legal","notices");
x.t("notice","legal");
x.t("2013","riverbed");
x.t("diagnosing","applications");
x.t("decodes","diagnosing");
x.t("software","may");
x.t("may","covered");
x.t("analyzing","network");
x.t("analyzing","diagnosing");
x.t("section","riverbed");
x.t("troubleshooting","patterns");
x.t("technology","software");
x.t("delays","protocol");
x.t("tier","delays");
x.t("protocol","decodes");
x.t("applications","user");
x.t("applications","appdoctor");
x.t("applications","analyzing");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("covered","u.s");
x.t("patterns","home");
x.t("patents","complete");
}
