function FileData_Pairs(x)
{
x.t("capturing","application");
x.t("home","back");
x.t("u.s","patents");
x.t("user","guide");
x.t("notices","section");
x.t("support","center");
x.t("wan-accelerated","capture");
x.t("wan-accelerated","environment");
x.t("back","top");
x.t("top","2013");
x.t("capture","data");
x.t("complete","patent");
x.t("wan","accelerators");
x.t("guide","wan");
x.t("traffic","wan-accelerated");
x.t("patent","notice");
x.t("legal","notices");
x.t("notice","legal");
x.t("importing","wan-accelerated");
x.t("2013","riverbed");
x.t("software","may");
x.t("may","covered");
x.t("section","riverbed");
x.t("environment","importing");
x.t("apptransaction","xpert");
x.t("technology","software");
x.t("data","home");
x.t("xpert","capturing");
x.t("application","traffic");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("accelerators","user");
x.t("accelerators","wan");
x.t("accelerators","apptransaction");
x.t("covered","u.s");
x.t("patents","complete");
}
