function FileData_Pairs(x)
{
x.t("home","back");
x.t("u.s","patents");
x.t("notices","section");
x.t("time","cx-tracer");
x.t("what\u2019s","new");
x.t("back","top");
x.t("new","release");
x.t("top","2014");
x.t("complete","patent");
x.t("enhancement","what\u2019s");
x.t("enhancement","asa");
x.t("enhancement","run");
x.t("patent","notice");
x.t("legal","notices");
x.t("notice","legal");
x.t("2014","riverbed");
x.t("software","may");
x.t("may","covered");
x.t("release","9.5");
x.t("section","riverbed");
x.t("9.5","asa");
x.t("technology","software");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("asa","boost");
x.t("run","asa");
x.t("cx-tracer","home");
x.t("covered","u.s");
x.t("boost","time");
x.t("boost","enhancement");
x.t("patents","complete");
}
