function FileData_Pairs(x)
{
x.t("home","back");
x.t("u.s","patents");
x.t("set","documentation");
x.t("notices","section");
x.t("support","center");
x.t("back","top");
x.t("top","2013");
x.t("complete","patent");
x.t("overview","using");
x.t("patent","notice");
x.t("solution","overview");
x.t("legal","notices");
x.t("notice","legal");
x.t("2013","riverbed");
x.t("software","may");
x.t("may","covered");
x.t("section","riverbed");
x.t("documentation","set");
x.t("documentation","effectively");
x.t("documentation","conventions");
x.t("effectively","home");
x.t("technology","software");
x.t("online","help");
x.t("help","solution");
x.t("help","documentation");
x.t("help","using");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("using","documentation");
x.t("using","online");
x.t("covered","u.s");
x.t("conventions","using");
x.t("patents","complete");
}
