function FileData_Pairs(x)
{
x.t("insights","introduction");
x.t("home","back");
x.t("u.s","patents");
x.t("notices","section");
x.t("introduction","insight");
x.t("slas","advanced");
x.t("back","top");
x.t("getting","started");
x.t("advanced","data");
x.t("top","2014");
x.t("complete","patent");
x.t("tutorials","getting");
x.t("tutorials","tutorials");
x.t("kit","home");
x.t("creating","custom");
x.t("custom","insights");
x.t("started","trending");
x.t("patent","notice");
x.t("legal","notices");
x.t("notice","legal");
x.t("trending","alerts");
x.t("reporting","slas");
x.t("2014","riverbed");
x.t("software","may");
x.t("may","covered");
x.t("section","riverbed");
x.t("insight","development");
x.t("alerts","reporting");
x.t("technology","software");
x.t("data","analysis");
x.t("riverbed","support");
x.t("riverbed","technology");
x.t("development","kit");
x.t("analysis","creating");
x.t("covered","u.s");
x.t("patents","complete");
}
